import type { SidebarConfig } from "@vuepress/theme-default";

export const hiSidebar: SidebarConfig = {
  "/hi/": [
    {
      title: "शुरू करें",
      collapsable: false,
      children: [
        "/hi/about/",
        "/hi/functions/",
        "/hi/paths/",
      ],
    },
    {
      title: "उपनाम",
      collapsable: false,
      children: [
        "/hi/aliases/",
        "/hi/aliases/ai/",
        "/hi/aliases/archives/",
        "/hi/aliases/cd/",
        "/hi/aliases/chmod/",
        "/hi/aliases/clear/",
        "/hi/aliases/compliance/",
        "/hi/aliases/configuration/",
        "/hi/aliases/default/",
        "/hi/aliases/diagnostics/",
        "/hi/aliases/dig/",
        "/hi/aliases/disk-usage/",
        "/hi/aliases/docker/",
        "/hi/aliases/editor/",
        "/hi/aliases/find/",
        "/hi/aliases/fonts/",
        "/hi/aliases/gcloud/",
        "/hi/aliases/git/",
        "/hi/aliases/gnu/",
        "/hi/aliases/go/",
        "/hi/aliases/heroku/",
        "/hi/aliases/installer/",
        "/hi/aliases/interactive/",
        "/hi/aliases/kubernetes/",
        "/hi/aliases/legal/",
        "/hi/aliases/lua/",
        "/hi/aliases/macOS/",
        "/hi/aliases/make/",
        "/hi/aliases/mkdir/",
        "/hi/aliases/modern/",
        "/hi/aliases/npm/",
        "/hi/aliases/permission/",
        "/hi/aliases/pnpm/",
        "/hi/aliases/ps/",
        "/hi/aliases/python/",
        "/hi/aliases/rsync/",
        "/hi/aliases/rust/",
        "/hi/aliases/security/",
        "/hi/aliases/subversion/",
        "/hi/aliases/sudo/",
        "/hi/aliases/terraform/",
        "/hi/aliases/tmux/",
        "/hi/aliases/update/",
        "/hi/aliases/uuid/",
        "/hi/aliases/wget/",
        "/hi/aliases/yarn/",
      ],
    },
  ],
};
