import type { SidebarConfig } from "@vuepress/theme-default";

export const idSidebar: SidebarConfig = {
  "/id/": [
    {
      title: "Memulai",
      collapsable: false,
      children: [
        "/id/about/",
        "/id/functions/",
        "/id/paths/",
      ],
    },
    {
      title: "Alias",
      collapsable: false,
      children: [
        "/id/aliases/",
        "/id/aliases/ai/",
        "/id/aliases/archives/",
        "/id/aliases/cd/",
        "/id/aliases/chmod/",
        "/id/aliases/clear/",
        "/id/aliases/compliance/",
        "/id/aliases/configuration/",
        "/id/aliases/default/",
        "/id/aliases/diagnostics/",
        "/id/aliases/dig/",
        "/id/aliases/disk-usage/",
        "/id/aliases/docker/",
        "/id/aliases/editor/",
        "/id/aliases/find/",
        "/id/aliases/fonts/",
        "/id/aliases/gcloud/",
        "/id/aliases/git/",
        "/id/aliases/gnu/",
        "/id/aliases/go/",
        "/id/aliases/heroku/",
        "/id/aliases/installer/",
        "/id/aliases/interactive/",
        "/id/aliases/kubernetes/",
        "/id/aliases/legal/",
        "/id/aliases/macOS/",
        "/id/aliases/make/",
        "/id/aliases/mkdir/",
        "/id/aliases/modern/",
        "/id/aliases/npm/",
        "/id/aliases/permission/",
        "/id/aliases/pnpm/",
        "/id/aliases/ps/",
        "/id/aliases/python/",
        "/id/aliases/rsync/",
        "/id/aliases/rust/",
        "/id/aliases/security/",
        "/id/aliases/subversion/",
        "/id/aliases/sudo/",
        "/id/aliases/terraform/",
        "/id/aliases/tmux/",
        "/id/aliases/update/",
        "/id/aliases/uuid/",
        "/id/aliases/wget/",
        "/id/aliases/yarn/",
      ],
    },
  ],
};
