import type { SidebarConfig } from "@vuepress/theme-default";

export const itSidebar: SidebarConfig = {
  "/it/": [
    {
      title: "Per Iniziare",
      collapsable: false,
      children: [
        "/it/about/",
        "/it/functions/",
        "/it/paths/",
      ],
    },
    {
      title: "Alias",
      collapsable: false,
      children: [
        "/it/aliases/",
        "/it/aliases/ai/",
        "/it/aliases/archives/",
        "/it/aliases/cd/",
        "/it/aliases/chmod/",
        "/it/aliases/clear/",
        "/it/aliases/compliance/",
        "/it/aliases/configuration/",
        "/it/aliases/default/",
        "/it/aliases/diagnostics/",
        "/it/aliases/dig/",
        "/it/aliases/disk-usage/",
        "/it/aliases/docker/",
        "/it/aliases/editor/",
        "/it/aliases/find/",
        "/it/aliases/fonts/",
        "/it/aliases/gcloud/",
        "/it/aliases/git/",
        "/it/aliases/gnu/",
        "/it/aliases/go/",
        "/it/aliases/heroku/",
        "/it/aliases/installer/",
        "/it/aliases/interactive/",
        "/it/aliases/kubernetes/",
        "/it/aliases/legal/",
        "/it/aliases/macOS/",
        "/it/aliases/make/",
        "/it/aliases/mkdir/",
        "/it/aliases/modern/",
        "/it/aliases/npm/",
        "/it/aliases/permission/",
        "/it/aliases/pnpm/",
        "/it/aliases/ps/",
        "/it/aliases/python/",
        "/it/aliases/rsync/",
        "/it/aliases/rust/",
        "/it/aliases/security/",
        "/it/aliases/subversion/",
        "/it/aliases/sudo/",
        "/it/aliases/terraform/",
        "/it/aliases/tmux/",
        "/it/aliases/update/",
        "/it/aliases/uuid/",
        "/it/aliases/wget/",
        "/it/aliases/yarn/",
      ],
    },
  ],
};
