import type { SidebarConfig } from "@vuepress/theme-default";

export const jaSidebar: SidebarConfig = {
  "/ja/": [
    {
      title: "はじめに",
      collapsable: false,
      children: [
        "/ja/about/",
        "/ja/functions/",
        "/ja/paths/",
      ],
    },
    {
      title: "エイリアス",
      collapsable: false,
      children: [
        "/ja/alias/",
        "/ja/alias/ai/",
        "/ja/alias/archives/",
        "/ja/alias/cd/",
        "/ja/alias/chmod/",
        "/ja/alias/clear/",
        "/ja/alias/compliance/",
        "/ja/alias/configuration/",
        "/ja/alias/default/",
        "/ja/alias/diagnostics/",
        "/ja/alias/dig/",
        "/ja/alias/disk-usage/",
        "/ja/alias/docker/",
        "/ja/alias/editor/",
        "/ja/alias/find/",
        "/ja/alias/fonts/",
        "/ja/alias/gcloud/",
        "/ja/alias/git/",
        "/ja/alias/gnu/",
        "/ja/alias/go/",
        "/ja/alias/heroku/",
        "/ja/alias/installer/",
        "/ja/alias/interactive/",
        "/ja/alias/kubernetes/",
        "/ja/alias/legal/",
        "/ja/alias/macOS/",
        "/ja/alias/make/",
        "/ja/alias/mkdir/",
        "/ja/alias/modern/",
        "/ja/alias/npm/",
        "/ja/alias/permission/",
        "/ja/alias/pnpm/",
        "/ja/alias/ps/",
        "/ja/alias/python/",
        "/ja/alias/rsync/",
        "/ja/alias/rust/",
        "/ja/alias/security/",
        "/ja/alias/subversion/",
        "/ja/alias/sudo/",
        "/ja/alias/terraform/",
        "/ja/alias/tmux/",
        "/ja/alias/update/",
        "/ja/alias/uuid/",
        "/ja/alias/wget/",
        "/ja/alias/yarn/",
      ],
    },
  ],
};
