import type { SidebarConfig } from "@vuepress/theme-default";

export const koSidebar: SidebarConfig = {
  "/ko/": [
    {
      title: "시작하기",
      collapsable: false,
      children: [
        "/ko/about/",
        "/ko/functions/",
        "/ko/paths/",
      ],
    },
    {
      title: "별칭",
      collapsable: false,
      children: [
        "/ko/alias/",
        "/ko/alias/ai/",
        "/ko/alias/archives/",
        "/ko/alias/cd/",
        "/ko/alias/chmod/",
        "/ko/alias/clear/",
        "/ko/alias/compliance/",
        "/ko/alias/configuration/",
        "/ko/alias/default/",
        "/ko/alias/diagnostics/",
        "/ko/alias/dig/",
        "/ko/alias/disk-usage/",
        "/ko/alias/docker/",
        "/ko/alias/editor/",
        "/ko/alias/find/",
        "/ko/alias/fonts/",
        "/ko/alias/gcloud/",
        "/ko/alias/git/",
        "/ko/alias/gnu/",
        "/ko/alias/go/",
        "/ko/alias/heroku/",
        "/ko/alias/installer/",
        "/ko/alias/interactive/",
        "/ko/alias/kubernetes/",
        "/ko/alias/legal/",
        "/ko/alias/macOS/",
        "/ko/alias/make/",
        "/ko/alias/mkdir/",
        "/ko/alias/modern/",
        "/ko/alias/npm/",
        "/ko/alias/permission/",
        "/ko/alias/pnpm/",
        "/ko/alias/ps/",
        "/ko/alias/python/",
        "/ko/alias/rsync/",
        "/ko/alias/rust/",
        "/ko/alias/security/",
        "/ko/alias/subversion/",
        "/ko/alias/sudo/",
        "/ko/alias/terraform/",
        "/ko/alias/tmux/",
        "/ko/alias/update/",
        "/ko/alias/uuid/",
        "/ko/alias/wget/",
        "/ko/alias/yarn/",
      ],
    },
  ],
};
