import type { SidebarConfig } from "@vuepress/theme-default";

export const nlSidebar: SidebarConfig = {
  "/nl/": [
    {
      title: "Aan de slag",
      collapsable: false,
      children: [
        "/nl/about/",
        "/nl/functions/",
        "/nl/paths/",
      ],
    },
    {
      title: "Aliassen",
      collapsable: false,
      children: [
        "/nl/aliases/",
        "/nl/aliases/ai/",
        "/nl/aliases/archives/",
        "/nl/aliases/cd/",
        "/nl/aliases/chmod/",
        "/nl/aliases/clear/",
        "/nl/aliases/compliance/",
        "/nl/aliases/configuration/",
        "/nl/aliases/default/",
        "/nl/aliases/diagnostics/",
        "/nl/aliases/dig/",
        "/nl/aliases/disk-usage/",
        "/nl/aliases/docker/",
        "/nl/aliases/editor/",
        "/nl/aliases/find/",
        "/nl/aliases/fonts/",
        "/nl/aliases/gcloud/",
        "/nl/aliases/git/",
        "/nl/aliases/gnu/",
        "/nl/aliases/go/",
        "/nl/aliases/heroku/",
        "/nl/aliases/installer/",
        "/nl/aliases/interactive/",
        "/nl/aliases/kubernetes/",
        "/nl/aliases/legal/",
        "/nl/aliases/macOS/",
        "/nl/aliases/make/",
        "/nl/aliases/mkdir/",
        "/nl/aliases/modern/",
        "/nl/aliases/npm/",
        "/nl/aliases/permission/",
        "/nl/aliases/pnpm/",
        "/nl/aliases/ps/",
        "/nl/aliases/python/",
        "/nl/aliases/rsync/",
        "/nl/aliases/rust/",
        "/nl/aliases/security/",
        "/nl/aliases/subversion/",
        "/nl/aliases/sudo/",
        "/nl/aliases/terraform/",
        "/nl/aliases/tmux/",
        "/nl/aliases/update/",
        "/nl/aliases/uuid/",
        "/nl/aliases/wget/",
        "/nl/aliases/yarn/",
      ],
    },
  ],
};
