export const aliases = {
  ariaLabel: "Aliase - Dotfiles",
  children: [
    ["/de/aliases/ai/", "Ai Aliase"],
    ["/de/aliases/archives/", "Archives Aliase"],
    ["/de/aliases/cd/", "Cd Aliase"],
    ["/de/aliases/chmod/", "Chmod Aliase"],
    ["/de/aliases/clear/", "Clear Aliase"],
    ["/de/aliases/compliance/", "Compliance Aliase"],
    ["/de/aliases/configuration/", "Configuration Aliase"],
    ["/de/aliases/default/", "Default Aliase"],
    ["/de/aliases/diagnostics/", "Diagnostics Aliase"],
    ["/de/aliases/dig/", "Dig Aliase"],
    ["/de/aliases/docker/", "Docker Aliase"],
    ["/de/aliases/dot/", "Dot Command"],
    ["/de/aliases/du/", "Du Aliase"],
    ["/de/aliases/editor/", "Editor Aliase"],
    ["/de/aliases/find/", "Find Aliase"],
    ["/de/aliases/fonts/", "Fonts Aliase"],
    ["/de/aliases/gcloud/", "GCloud Aliase"],
    ["/de/aliases/git/", "Git Aliase"],
    ["/de/aliases/gnu/", "Gnu Aliase"],
    ["/de/aliases/go/", "Go Aliase"],
    ["/de/aliases/installer/", "Installer Aliase"],
    ["/de/aliases/interactive/", "Interactive Aliase"],
    ["/de/aliases/jekyll/", "Jekyll Aliase"],
    ["/de/aliases/kubernetes/", "Kubernetes Aliase"],
    ["/de/aliases/legal/", "Legal Aliase"],
    ["/de/aliases/list/", "List Aliase"],
    ["/de/aliases/macOS/", "macOS Aliase"],
    ["/de/aliases/make/", "Make Aliase"],
    ["/de/aliases/mkdir/", "Mkdir Aliase"],
    ["/de/aliases/modern/", "Modern Unix"],
    ["/de/aliases/modern-core/", "Modern Core"],
    ["/de/aliases/npm/", "NPM Aliase"],
    ["/de/aliases/permission/", "Permission Aliase"],
    ["/de/aliases/pnpm/", "pnpm Aliase"],
    ["/de/aliases/ps/", "Ps Aliase"],
    ["/de/aliases/python/", "Python Aliase"],
    ["/de/aliases/rsync/", "Rsync Aliase"],
    ["/de/aliases/rust/", "Rust Aliase"],
    ["/de/aliases/security/", "Security Aliase"],
    ["/de/aliases/subversion/", "Subversion Aliase"],
    ["/de/aliases/sudo/", "Sudo Aliase"],
    ["/de/aliases/terraform/", "Terraform Aliase"],
    ["/de/aliases/tmux/", "Tmux Aliase"],
    ["/de/aliases/update/", "Update Aliase"],
    ["/de/aliases/uuid/", "UUID Aliase"],
    ["/de/aliases/wget/", "Wget Aliase"],
    ["/de/aliases/yarn/", "Yarn Aliase"],
  ],
  collapsable: false,
  path: "/de/aliases/",
  title: "Aliase",
};
