export const aliases = {
  ariaLabel: "Aliases - Dotfiles",
  children: [
    ["/aliases/archives/", "Archives aliases"],
    ["/aliases/cd/", "Cd aliases"],
    ["/aliases/chmod/", "Chmod aliases"],
    ["/aliases/clear/", "Clear aliases"],
    ["/aliases/configuration/", "Configuration aliases"],
    ["/aliases/default/", "Default aliases"],
    ["/aliases/dig/", "Dig aliases"],
    ["/aliases/dot/", "Dot Command"],
    ["/aliases/du/", "Disk usage aliases"],
    ["/aliases/editor/", "Editor aliases"],
    ["/aliases/find/", "Find aliases"],
    ["/aliases/gcloud/", "GCloud aliases"],
    ["/aliases/git/", "Git aliases"],
    ["/aliases/gnu/", "GNU Core Utilities aliases"],
    ["/aliases/heroku/", "Heroku aliases"],
    ["/aliases/interactive/", "Interactive aliases"],
    ["/aliases/jekyll/", "Jekyll aliases"],
    ["/aliases/list/", "List aliases"],
    ["/aliases/make/", "Make aliases"],
    ["/aliases/mkdir/", "Mkdir aliases"],
    ["/aliases/modern-core/", "Modern Core"],
    ["/aliases/npm/", "NPM aliases"],
    ["/aliases/pnpm/", "pnpm aliases"],
    ["/aliases/ps/", "PS aliases"],
    ["/aliases/rsync/", "Rsync aliases"],
    ["/aliases/rust/", "Rust aliases"],
    ["/aliases/subversion/", "Subversion aliases"],
    ["/aliases/sudo/", "Sudo aliases"],
    ["/aliases/tmux/", "Tmux aliases"],
    ["/aliases/update/", "Update aliases"],
    ["/aliases/uuid/", "UUID aliases"],
    ["/aliases/wget/", "Wget aliases"],
  ],
  collapsable: false,
  path: "/aliases/",
  title: "Aliases",
};
