export const aliases = {
  ariaLabel: 'Aliases',
  children: [
    ["/aliases/archives/", "❯ Archives aliases"],
    ["/aliases/clear/", "❯ Clear aliases"],
    ["/aliases/configuration/", "❯ Configuration aliases"],
    ["/aliases/default/", "❯ Default aliases"],
    ["/aliases/dig/", "❯ Dig aliases"],
    ["/aliases/diskusage/", "❯ Disk usage aliases"],
    ["/aliases/editor/", "❯ Editor aliases"],
    ["/aliases/find/", "❯ Find aliases"],
    ["/aliases/gcloud/", "❯ GCloud aliases"],
    ["/aliases/git/", "❯ Git aliases"],
    ["/aliases/gnu/", "❯ GNU Core Utilities aliases"],
    ["/aliases/heroku/", "❯ Heroku aliases"],
    ["/aliases/interactive/", "❯ Interactive aliases"],
    ["/aliases/jekyll/", "❯ Jekyll aliases"],
    ["/aliases/list/", "❯ List aliases"],
    ["/aliases/make/", "❯ Make aliases"],
    ["/aliases/mkdir/", "❯ Mkdir aliases"],
    ["/aliases/pnpm/", "❯ PNPM aliases"],
    ["/aliases/subversion/", "❯ Subversion aliases"],
    ["/aliases/tmux/", "❯ Tmux aliases"],
  ],
  collapsable: false,
  path: '/aliases/',
  title: 'Aliases',
}
