export const aliases = {
  ariaLabel: "Alias - Dotfiles",
  children: [
    ["/es/aliases/ai/", "Inteligencia Artificial"],
    ["/es/aliases/archives/", "Archivos"],
    ["/es/aliases/cd/", "Directorios (cd)"],
    ["/es/aliases/chmod/", "Permisos (chmod)"],
    ["/es/aliases/clear/", "Limpiar (clear)"],
    ["/es/aliases/compliance/", "Cumplimiento"],
    ["/es/aliases/configuration/", "Configuración"],
    ["/es/aliases/default/", "Predeterminado"],
    ["/es/aliases/diagnostics/", "Diagnóstico"],
    ["/es/aliases/dig/", "DNS (dig)"],
    ["/es/aliases/disk-usage/", "Uso de Disco"],
    ["/es/aliases/docker/", "Docker"],
    ["/es/aliases/editor/", "Editor"],
    ["/es/aliases/find/", "Búsqueda (find)"],
    ["/es/aliases/fonts/", "Fuentes"],
    ["/es/aliases/gcloud/", "Google Cloud"],
    ["/es/aliases/git/", "Git"],
    ["/es/aliases/gnu/", "Utilidades GNU"],
    ["/es/aliases/go/", "Go"],
    ["/es/aliases/heroku/", "Heroku"],
    ["/es/aliases/installer/", "Instalador"],
    ["/es/aliases/interactive/", "Interactivo"],
    ["/es/aliases/kubernetes/", "Kubernetes"],
    ["/es/aliases/legal/", "Legal"],
    ["/es/aliases/macOS/", "macOS"],
    ["/es/aliases/make/", "Make"],
    ["/es/aliases/mkdir/", "Directorios (mkdir)"],
    ["/es/aliases/modern/", "Unix Moderno"],
    ["/es/aliases/npm/", "NPM"],
    ["/es/aliases/permission/", "Permisos"],
    ["/es/aliases/pnpm/", "PNPM"],
    ["/es/aliases/ps/", "Procesos (ps)"],
    ["/es/aliases/python/", "Python"],
    ["/es/aliases/rsync/", "Rsync"],
    ["/es/aliases/rust/", "Rust"],
    ["/es/aliases/security/", "Seguridad"],
    ["/es/aliases/subversion/", "Subversion"],
    ["/es/aliases/sudo/", "Sudo"],
    ["/es/aliases/terraform/", "Terraform"],
    ["/es/aliases/tmux/", "Tmux"],
    ["/es/aliases/update/", "Actualización"],
    ["/es/aliases/uuid/", "UUID"],
    ["/es/aliases/wget/", "Wget"],
    ["/es/aliases/yarn/", "Yarn"],
  ],
  collapsable: false,
  path: "/es/aliases/",
  title: "Alias",
};
