export const aliases = {
  ariaLabel: "Alias - Dotfiles",
  children: [
    ["/es/aliases/ai/", "Ai Alias"],
    ["/es/aliases/archives/", "Archives Alias"],
    ["/es/aliases/cd/", "Cd Alias"],
    ["/es/aliases/chmod/", "Chmod Alias"],
    ["/es/aliases/clear/", "Clear Alias"],
    ["/es/aliases/compliance/", "Compliance Alias"],
    ["/es/aliases/configuration/", "Configuration Alias"],
    ["/es/aliases/default/", "Default Alias"],
    ["/es/aliases/diagnostics/", "Diagnostics Alias"],
    ["/es/aliases/dig/", "Dig Alias"],
    ["/es/aliases/docker/", "Docker Alias"],
    ["/es/aliases/dot/", "Dot Command"],
    ["/es/aliases/du/", "Du Alias"],
    ["/es/aliases/editor/", "Editor Alias"],
    ["/es/aliases/find/", "Find Alias"],
    ["/es/aliases/fonts/", "Fonts Alias"],
    ["/es/aliases/gcloud/", "GCloud Alias"],
    ["/es/aliases/git/", "Git Alias"],
    ["/es/aliases/gnu/", "Gnu Alias"],
    ["/es/aliases/go/", "Go Alias"],
    ["/es/aliases/heroku/", "Heroku Alias"],
    ["/es/aliases/installer/", "Installer Alias"],
    ["/es/aliases/interactive/", "Interactive Alias"],
    ["/es/aliases/jekyll/", "Jekyll Alias"],
    ["/es/aliases/kubernetes/", "Kubernetes Alias"],
    ["/es/aliases/legal/", "Legal Alias"],
    ["/es/aliases/list/", "List Alias"],
    ["/es/aliases/macOS/", "macOS Alias"],
    ["/es/aliases/make/", "Make Alias"],
    ["/es/aliases/mkdir/", "Mkdir Alias"],
    ["/es/aliases/modern/", "Modern Unix"],
    ["/es/aliases/modern-core/", "Modern Core"],
    ["/es/aliases/npm/", "NPM Alias"],
    ["/es/aliases/permission/", "Permission Alias"],
    ["/es/aliases/pnpm/", "pnpm Alias"],
    ["/es/aliases/ps/", "Ps Alias"],
    ["/es/aliases/python/", "Python Alias"],
    ["/es/aliases/rsync/", "Rsync Alias"],
    ["/es/aliases/rust/", "Rust Alias"],
    ["/es/aliases/security/", "Security Alias"],
    ["/es/aliases/subversion/", "Subversion Alias"],
    ["/es/aliases/sudo/", "Sudo Alias"],
    ["/es/aliases/terraform/", "Terraform Alias"],
    ["/es/aliases/tmux/", "Tmux Alias"],
    ["/es/aliases/update/", "Update Alias"],
    ["/es/aliases/uuid/", "UUID Alias"],
    ["/es/aliases/wget/", "Wget Alias"],
    ["/es/aliases/yarn/", "Yarn Alias"],
  ],
  collapsable: false,
  path: "/es/aliases/",
  title: "Alias",
};
