export const alias = {
  ariaLabel: 'Les alias Dotfiles',
  children: [
    ["/fr/alias/archives/", "les alias d'archivage"],
    ["/fr/alias/cd/", "les alias cd"],
    ["/fr/alias/chmod/", "les alias chmod"],
    ["/fr/alias/clear/", "les alias clear"],
    ["/fr/alias/configuration/", "les alias de configuration"],
    ["/fr/alias/default/", "les alias par défaut"],
    ["/fr/alias/dig/", "les alias dig"],
    ["/fr/alias/du/", "les alias du"],
    ["/fr/alias/editeur/", "les alias de l'éditeur système"],
    ["/fr/alias/gcloud/", "les alias gcloud"],
    ["/fr/alias/git/", "les alias git"],
    ["/fr/alias/gnu/", "les alias gnu coreutils"],
    ["/fr/alias/heroku/", "les alias heroku"],
    ["/fr/alias/jekyll/", "les alias jekyll"],
    ["/fr/alias/liste/", "les alias de liste"],
    ["/fr/alias/make/", "les alias make"],
    ["/fr/alias/mise-a-jour/", "les alias de mise à jour"],
    ["/fr/alias/mkdir/", "les alias mkdir"],
    ["/fr/alias/mode-interactif/", "les alias en mode interactif"],
    ["/fr/alias/npm/", "les alias npm"],
    ["/fr/alias/pnpm/", "les alias pnpm"],
    ["/fr/alias/ps/", "les alias ps"],
    ["/fr/alias/recherche/", "les alias de recherche"],
    ["/fr/alias/rsync/", "les alias rsync"],
    ["/fr/alias/rust/", "les alias rust"],
    ["/fr/alias/subversion/", "les alias subversion"],
    ["/fr/alias/sudo/", "les alias sudo"],
    ["/fr/alias/tmux/", "les alias tmux"],
    ["/fr/alias/uuid/", "les alias uuid"],
    ["/fr/alias/wget/", "les alias wget"],
  ],
  collapsable: false,
  path: '/fr/alias/',
  title: 'Les alias Dotfiles',

}
