export const alias = {
  ariaLabel: 'Les alias Dotfiles',
  children: [
    ["/fr/alias/archives/", "Les alias d'archivage"],
    ["/fr/alias/cd/", "Les alias cd"],
    ["/fr/alias/chmod/", "Les alias chmod"],
    ["/fr/alias/clear/", "Les alias clear"],
    ["/fr/alias/configuration/", "Les alias de configuration"],
    ["/fr/alias/default/", "Les alias par défaut"],
    ["/fr/alias/dig/", "Les alias dig"],
    ["/fr/alias/du/", "Les alias du"],
    ["/fr/alias/editor/", "Les alias editor"],
    ["/fr/alias/recherche/", "Les alias de recherche"],
    ["/fr/alias/gcloud/", "Les alias gcloud"],
    ["/fr/alias/git/", "Les alias git"],
    // ["/fr/alias/gnu/", "Les alias gnu"],
    // ["/fr/alias/heroku/", "Les alias heroku"],
    // ["/fr/alias/interactive/", "Les alias interactif"],
    // ["/fr/alias/jekyll/", "Les alias jekyll"],
    // ["/fr/alias/list/", "Les alias list"],
    // ["/fr/alias/make/", "Les alias make"],
    // ["/fr/alias/mkdir/", "Les alias mkdir"],
    // ["/fr/alias/npm/", "Les alias npm"],
    // ["/fr/alias/pnpm/", "Les alias pnpm"],
    // ["/fr/alias/ps/", "Les alias ps"],
    // ["/fr/alias/rsync/", "Les alias rsync"],
    // ["/fr/alias/rust/", "Les alias rust"],
    // ["/fr/alias/subversion/", "Les alias subversion"],
    // ["/fr/alias/sudo/", "Les alias sudo"],
    // ["/fr/alias/tmux/", "Les alias tmux"],
    // ["/fr/alias/update/", "Les alias update"],
    // ["/fr/alias/uuid/", "Les alias uuid"],
    // ["/fr/alias/wget/", "Les alias wget"],
  ],
  collapsable: false,
  path: '/fr/alias/',
  title: 'Les alias Dotfiles',

}
