export const alias = {
  ariaLabel: "Les alias Dotfiles",
  children: [
    ["/fr/aliases/ai/", "les alias IA"],
    ["/fr/aliases/archives/", "les alias d'archivage"],
    ["/fr/aliases/cd/", "les alias cd"],
    ["/fr/aliases/chmod/", "les alias chmod"],
    ["/fr/aliases/clear/", "les alias clear"],
    ["/fr/aliases/compliance/", "les alias de conformité"],
    ["/fr/aliases/configuration/", "les alias de configuration"],
    ["/fr/aliases/default/", "les alias par défaut"],
    ["/fr/aliases/diagnostics/", "les alias de diagnostic"],
    ["/fr/aliases/dig/", "les alias dig"],
    ["/fr/aliases/disk-usage/", "les alias disk-usage"],
    ["/fr/aliases/docker/", "les alias docker"],
    ["/fr/aliases/editor/", "les alias de l'éditeur système"],
    ["/fr/aliases/find/", "les alias de recherche"],
    ["/fr/aliases/fonts/", "les alias de polices"],
    ["/fr/aliases/gcloud/", "les alias gcloud"],
    ["/fr/aliases/git/", "les alias git"],
    ["/fr/aliases/gnu/", "les alias gnu coreutils"],
    ["/fr/aliases/go/", "les alias go"],
    ["/fr/aliases/heroku/", "les alias heroku"],
    ["/fr/aliases/installer/", "les alias d'installation"],
    ["/fr/aliases/interactive/", "les alias en mode interactif"],
    ["/fr/aliases/kubernetes/", "les alias kubernetes"],
    ["/fr/aliases/legal/", "les alias juridiques"],
    ["/fr/aliases/macOS/", "les alias macOS"],
    ["/fr/aliases/make/", "les alias make"],
    ["/fr/aliases/mkdir/", "les alias mkdir"],
    ["/fr/aliases/modern/", "les alias Unix moderne"],
    ["/fr/aliases/npm/", "les alias npm"],
    ["/fr/aliases/permission/", "les alias de permission"],
    ["/fr/aliases/pnpm/", "les alias pnpm"],
    ["/fr/aliases/ps/", "les alias ps"],
    ["/fr/aliases/python/", "les alias python"],
    ["/fr/aliases/rsync/", "les alias rsync"],
    ["/fr/aliases/rust/", "les alias rust"],
    ["/fr/aliases/security/", "les alias de sécurité"],
    ["/fr/aliases/subversion/", "les alias subversion"],
    ["/fr/aliases/sudo/", "les alias sudo"],
    ["/fr/aliases/terraform/", "les alias terraform"],
    ["/fr/aliases/tmux/", "les alias tmux"],
    ["/fr/aliases/update/", "les alias de mise à jour"],
    ["/fr/aliases/uuid/", "les alias uuid"],
    ["/fr/aliases/wget/", "les alias wget"],
    ["/fr/aliases/yarn/", "les alias yarn"],
  ],
  collapsable: false,
  path: "/fr/aliases/",
  title: "Les alias Dotfiles",
};
