export const aliases = {
  ariaLabel: "Alias - Dotfiles",
  children: [
    ["/it/aliases/ai/", "Alias AI"],
    ["/it/aliases/archives/", "Alias Archivi"],
    ["/it/aliases/cd/", "Alias Cd"],
    ["/it/aliases/chmod/", "Alias Chmod"],
    ["/it/aliases/clear/", "Alias Clear"],
    ["/it/aliases/compliance/", "Alias Conformità"],
    ["/it/aliases/configuration/", "Alias Configurazione"],
    ["/it/aliases/default/", "Alias Predefiniti"],
    ["/it/aliases/diagnostics/", "Alias Diagnostica"],
    ["/it/aliases/dig/", "Alias Dig"],
    ["/it/aliases/disk-usage/", "Alias Utilizzo Disco"],
    ["/it/aliases/docker/", "Alias Docker"],
    ["/it/aliases/editor/", "Alias Editor"],
    ["/it/aliases/find/", "Alias Find"],
    ["/it/aliases/fonts/", "Alias Font"],
    ["/it/aliases/gcloud/", "Alias GCloud"],
    ["/it/aliases/git/", "Alias Git"],
    ["/it/aliases/gnu/", "Alias GNU Core Utilities"],
    ["/it/aliases/go/", "Alias Go"],
    ["/it/aliases/heroku/", "Alias Heroku"],
    ["/it/aliases/installer/", "Alias Programma di Installazione"],
    ["/it/aliases/interactive/", "Alias Interattivi"],
    ["/it/aliases/kubernetes/", "Alias Kubernetes"],
    ["/it/aliases/legal/", "Alias Legale"],
    ["/it/aliases/macOS/", "Alias macOS"],
    ["/it/aliases/make/", "Alias Make"],
    ["/it/aliases/mkdir/", "Alias Mkdir"],
    ["/it/aliases/modern/", "Alias Unix Moderno"],
    ["/it/aliases/npm/", "Alias NPM"],
    ["/it/aliases/permission/", "Alias Permessi"],
    ["/it/aliases/pnpm/", "Alias pnpm"],
    ["/it/aliases/ps/", "Alias PS"],
    ["/it/aliases/python/", "Alias Python"],
    ["/it/aliases/rsync/", "Alias Rsync"],
    ["/it/aliases/rust/", "Alias Rust"],
    ["/it/aliases/security/", "Alias Sicurezza"],
    ["/it/aliases/subversion/", "Alias Subversion"],
    ["/it/aliases/sudo/", "Alias Sudo"],
    ["/it/aliases/terraform/", "Alias Terraform"],
    ["/it/aliases/tmux/", "Alias Tmux"],
    ["/it/aliases/update/", "Alias Aggiornamento"],
    ["/it/aliases/uuid/", "Alias UUID"],
    ["/it/aliases/wget/", "Alias Wget"],
    ["/it/aliases/yarn/", "Alias Yarn"],
  ],
  collapsable: false,
  path: "/it/aliases/",
  title: "Alias",
};