export const aliases = {
  ariaLabel: "エイリアス - Dotfiles",
  children: [
    ["/ja/alias/ai/", "AI エイリアス"],
    ["/ja/alias/archives/", "アーカイブエイリアス"],
    ["/ja/alias/cd/", "Cd エイリアス"],
    ["/ja/alias/chmod/", "Chmod エイリアス"],
    ["/ja/alias/clear/", "Clear エイリアス"],
    ["/ja/alias/compliance/", "コンプライアンスエイリアス"],
    ["/ja/alias/configuration/", "設定エイリアス"],
    ["/ja/alias/default/", "デフォルトエイリアス"],
    ["/ja/alias/diagnostics/", "診断エイリアス"],
    ["/ja/alias/dig/", "Dig エイリアス"],
    ["/ja/alias/disk-usage/", "ディスク使用量エイリアス"],
    ["/ja/alias/docker/", "Docker エイリアス"],
    ["/ja/alias/editor/", "エディターエイリアス"],
    ["/ja/alias/find/", "検索エイリアス"],
    ["/ja/alias/fonts/", "フォントエイリアス"],
    ["/ja/alias/gcloud/", "GCloud エイリアス"],
    ["/ja/alias/git/", "Git エイリアス"],
    ["/ja/alias/gnu/", "GNU Core Utilities エイリアス"],
    ["/ja/alias/go/", "Go エイリアス"],
    ["/ja/alias/heroku/", "Heroku エイリアス"],
    ["/ja/alias/installer/", "インストーラーエイリアス"],
    ["/ja/alias/interactive/", "インタラクティブエイリアス"],
    ["/ja/alias/kubernetes/", "Kubernetes エイリアス"],
    ["/ja/alias/legal/", "リーガルエイリアス"],
    ["/ja/alias/macOS/", "macOS エイリアス"],
    ["/ja/alias/make/", "Make エイリアス"],
    ["/ja/alias/mkdir/", "Mkdir エイリアス"],
    ["/ja/alias/modern/", "モダン Unix"],
    ["/ja/alias/npm/", "NPM エイリアス"],
    ["/ja/alias/permission/", "権限エイリアス"],
    ["/ja/alias/pnpm/", "pnpm エイリアス"],
    ["/ja/alias/ps/", "PS エイリアス"],
    ["/ja/alias/python/", "Python エイリアス"],
    ["/ja/alias/rsync/", "Rsync エイリアス"],
    ["/ja/alias/rust/", "Rust エイリアス"],
    ["/ja/alias/security/", "セキュリティエイリアス"],
    ["/ja/alias/subversion/", "Subversion エイリアス"],
    ["/ja/alias/sudo/", "Sudo エイリアス"],
    ["/ja/alias/terraform/", "Terraform エイリアス"],
    ["/ja/alias/tmux/", "Tmux エイリアス"],
    ["/ja/alias/update/", "更新エイリアス"],
    ["/ja/alias/uuid/", "UUID エイリアス"],
    ["/ja/alias/wget/", "Wget エイリアス"],
    ["/ja/alias/yarn/", "Yarn エイリアス"],
  ],
  collapsable: false,
  path: "/ja/alias/",
  title: "エイリアス",
};