export const aliases = {
  ariaLabel: "별칭 - Dotfiles",
  children: [
    ["/ko/alias/ai/", "AI 별칭"],
    ["/ko/alias/archives/", "아카이브 별칭"],
    ["/ko/alias/cd/", "Cd 별칭"],
    ["/ko/alias/chmod/", "Chmod 별칭"],
    ["/ko/alias/clear/", "Clear 별칭"],
    ["/ko/alias/compliance/", "규정 준수 별칭"],
    ["/ko/alias/configuration/", "구성 별칭"],
    ["/ko/alias/default/", "기본 별칭"],
    ["/ko/alias/diagnostics/", "진단 별칭"],
    ["/ko/alias/dig/", "Dig 별칭"],
    ["/ko/alias/disk-usage/", "디스크 사용량 별칭"],
    ["/ko/alias/docker/", "Docker 별칭"],
    ["/ko/alias/editor/", "에디터 별칭"],
    ["/ko/alias/find/", "찾기 별칭"],
    ["/ko/alias/fonts/", "글꼴 별칭"],
    ["/ko/alias/gcloud/", "GCloud 별칭"],
    ["/ko/alias/git/", "Git 별칭"],
    ["/ko/alias/gnu/", "GNU Core Utilities 별칭"],
    ["/ko/alias/go/", "Go 별칭"],
    ["/ko/alias/heroku/", "Heroku 별칭"],
    ["/ko/alias/installer/", "설치 프로그램 별칭"],
    ["/ko/alias/interactive/", "대화형 별칭"],
    ["/ko/alias/kubernetes/", "Kubernetes 별칭"],
    ["/ko/alias/legal/", "법률 별칭"],
    ["/ko/alias/macOS/", "macOS 별칭"],
    ["/ko/alias/make/", "Make 별칭"],
    ["/ko/alias/mkdir/", "Mkdir 별칭"],
    ["/ko/alias/modern/", "모던 Unix"],
    ["/ko/alias/npm/", "NPM 별칭"],
    ["/ko/alias/permission/", "권한 별칭"],
    ["/ko/alias/pnpm/", "pnpm 별칭"],
    ["/ko/alias/ps/", "PS 별칭"],
    ["/ko/alias/python/", "Python 별칭"],
    ["/ko/alias/rsync/", "Rsync 별칭"],
    ["/ko/alias/rust/", "Rust 별칭"],
    ["/ko/alias/security/", "보안 별칭"],
    ["/ko/alias/subversion/", "Subversion 별칭"],
    ["/ko/alias/sudo/", "Sudo 별칭"],
    ["/ko/alias/terraform/", "Terraform 별칭"],
    ["/ko/alias/tmux/", "Tmux 별칭"],
    ["/ko/alias/update/", "업데이트 별칭"],
    ["/ko/alias/uuid/", "UUID 별칭"],
    ["/ko/alias/wget/", "Wget 별칭"],
    ["/ko/alias/yarn/", "Yarn 별칭"],
  ],
  collapsable: false,
  path: "/ko/alias/",
  title: "별칭",
};