export const aliases = {
  ariaLabel: "Aliases - Dotfiles",
  children: [
    ["/pt/aliases/ai/", "Ai Aliases"],
    ["/pt/aliases/archives/", "Archives Aliases"],
    ["/pt/aliases/cd/", "Cd Aliases"],
    ["/pt/aliases/chmod/", "Chmod Aliases"],
    ["/pt/aliases/clear/", "Clear Aliases"],
    ["/pt/aliases/compliance/", "Compliance Aliases"],
    ["/pt/aliases/configuration/", "Configuration Aliases"],
    ["/pt/aliases/default/", "Default Aliases"],
    ["/pt/aliases/diagnostics/", "Diagnostics Aliases"],
    ["/pt/aliases/dig/", "Dig Aliases"],
    ["/pt/aliases/docker/", "Docker Aliases"],
    ["/pt/aliases/dot/", "Dot Command"],
    ["/pt/aliases/du/", "Du Aliases"],
    ["/pt/aliases/editor/", "Editor Aliases"],
    ["/pt/aliases/find/", "Find Aliases"],
    ["/pt/aliases/fonts/", "Fonts Aliases"],
    ["/pt/aliases/gcloud/", "GCloud Aliases"],
    ["/pt/aliases/git/", "Git Aliases"],
    ["/pt/aliases/gnu/", "Gnu Aliases"],
    ["/pt/aliases/go/", "Go Aliases"],
    ["/pt/aliases/heroku/", "Heroku Aliases"],
    ["/pt/aliases/installer/", "Installer Aliases"],
    ["/pt/aliases/interactive/", "Interactive Aliases"],
    ["/pt/aliases/jekyll/", "Jekyll Aliases"],
    ["/pt/aliases/kubernetes/", "Kubernetes Aliases"],
    ["/pt/aliases/legal/", "Legal Aliases"],
    ["/pt/aliases/list/", "List Aliases"],
    ["/pt/aliases/macOS/", "macOS Aliases"],
    ["/pt/aliases/make/", "Make Aliases"],
    ["/pt/aliases/mkdir/", "Mkdir Aliases"],
    ["/pt/aliases/modern/", "Modern Unix"],
    ["/pt/aliases/modern-core/", "Modern Core"],
    ["/pt/aliases/npm/", "NPM Aliases"],
    ["/pt/aliases/permission/", "Permission Aliases"],
    ["/pt/aliases/pnpm/", "pnpm Aliases"],
    ["/pt/aliases/ps/", "Ps Aliases"],
    ["/pt/aliases/python/", "Python Aliases"],
    ["/pt/aliases/rsync/", "Rsync Aliases"],
    ["/pt/aliases/rust/", "Rust Aliases"],
    ["/pt/aliases/security/", "Security Aliases"],
    ["/pt/aliases/subversion/", "Subversion Aliases"],
    ["/pt/aliases/sudo/", "Sudo Aliases"],
    ["/pt/aliases/terraform/", "Terraform Aliases"],
    ["/pt/aliases/tmux/", "Tmux Aliases"],
    ["/pt/aliases/update/", "Update Aliases"],
    ["/pt/aliases/uuid/", "UUID Aliases"],
    ["/pt/aliases/wget/", "Wget Aliases"],
    ["/pt/aliases/yarn/", "Yarn Aliases"],
  ],
  collapsable: false,
  path: "/pt/aliases/",
  title: "Aliases",
};
