export const aliases = {
  ariaLabel: "别名 - Dotfiles",
  children: [
    ["/zh/aliases/ai/", "Ai 别名"],
    ["/zh/aliases/archives/", "Archives 别名"],
    ["/zh/aliases/cd/", "Cd 别名"],
    ["/zh/aliases/chmod/", "Chmod 别名"],
    ["/zh/aliases/clear/", "Clear 别名"],
    ["/zh/aliases/compliance/", "Compliance 别名"],
    ["/zh/aliases/configuration/", "Configuration 别名"],
    ["/zh/aliases/default/", "Default 别名"],
    ["/zh/aliases/diagnostics/", "Diagnostics 别名"],
    ["/zh/aliases/dig/", "Dig 别名"],
    ["/zh/aliases/docker/", "Docker 别名"],
    ["/zh/aliases/dot/", "Dot Command"],
    ["/zh/aliases/du/", "Du 别名"],
    ["/zh/aliases/editor/", "Editor 别名"],
    ["/zh/aliases/find/", "Find 别名"],
    ["/zh/aliases/fonts/", "Fonts 别名"],
    ["/zh/aliases/gcloud/", "GCloud 别名"],
    ["/zh/aliases/git/", "Git 别名"],
    ["/zh/aliases/gnu/", "Gnu 别名"],
    ["/zh/aliases/go/", "Go 别名"],
    ["/zh/aliases/installer/", "Installer 别名"],
    ["/zh/aliases/interactive/", "Interactive 别名"],
    ["/zh/aliases/jekyll/", "Jekyll 别名"],
    ["/zh/aliases/kubernetes/", "Kubernetes 别名"],
    ["/zh/aliases/legal/", "Legal 别名"],
    ["/zh/aliases/list/", "List 别名"],
    ["/zh/aliases/macOS/", "macOS 别名"],
    ["/zh/aliases/make/", "Make 别名"],
    ["/zh/aliases/mkdir/", "Mkdir 别名"],
    ["/zh/aliases/modern/", "Modern Unix"],
    ["/zh/aliases/modern-core/", "Modern Core"],
    ["/zh/aliases/npm/", "NPM 别名"],
    ["/zh/aliases/permission/", "Permission 别名"],
    ["/zh/aliases/pnpm/", "pnpm 别名"],
    ["/zh/aliases/ps/", "Ps 别名"],
    ["/zh/aliases/python/", "Python 别名"],
    ["/zh/aliases/rsync/", "Rsync 别名"],
    ["/zh/aliases/rust/", "Rust 别名"],
    ["/zh/aliases/security/", "Security 别名"],
    ["/zh/aliases/subversion/", "Subversion 别名"],
    ["/zh/aliases/sudo/", "Sudo 别名"],
    ["/zh/aliases/terraform/", "Terraform 别名"],
    ["/zh/aliases/tmux/", "Tmux 别名"],
    ["/zh/aliases/update/", "Update 别名"],
    ["/zh/aliases/uuid/", "UUID 别名"],
    ["/zh/aliases/wget/", "Wget 别名"],
    ["/zh/aliases/yarn/", "Yarn 别名"],
  ],
  collapsable: false,
  path: "/zh/aliases/",
  title: "别名",
};
