export const headers: string[] = [
  ["link", { rel: "apple-touch-icon", sizes: "192x192", href: "/icons/dotfiles-192x192.png" }],
  ["link", { rel: "apple-touch-icon", sizes: "152x152", href: "/icons/apple-touch-icon-152x152.png" }],
  ["link", { rel: "apple-touch-icon", sizes: "180x180", href: "/icons/apple-touch-icon.png" }],
  ["link", { rel: "icon", type: "image/png", sizes: "16x16", href: "/icons/favicon-16x16.png" }],
  ["link", { rel: "icon", type: "image/png", sizes: "32x32", href: "/icons/favicon-32x32.png" }],
  ["link", { rel: "manifest", href: "/manifest.json" }],
  ["link", { rel: "preload", href: "https://unpkg.com/skeletonic-stylus@1.0.5/css/skeletonic-fonts.min.css", as: "style", onload: "this.onload=null;this.rel='stylesheet'" }],
  ["link", { rel: "shortcut icon", href: "/icons/favicon.ico" }],
  ["meta", { "http-equiv": "Cache-Control", content: "no-cache, no-store, must-revalidate" }],
  ["meta", { "http-equiv": "Expires", content: "0" }],
  ["meta", { "http-equiv": "Pragma", content: "no-cache" }],
  ["meta", { "http-equiv": "X-UA-Compatible", content: "IE=edge" }],
  ["meta", { itemprop: "accessibilityAPI", content: "ARIA" }],
  ["meta", { itemprop: "accessibilityControl", content: "fullKeyboardControl" }],
  ["meta", { itemprop: "accessibilityControl", content: "fullMouseControl" }],
  ["meta", { itemprop: "accessibilityHazard", content: "noFlashingHazard" }],
  ["meta", { itemprop: "accessibilityHazard", content: "noMotionSimulationHazard" }],
  ["meta", { itemprop: "accessibilityHazard", content: "noSoundHazard" }],
  ["meta", { name: "apple-mobile-web-app-capable", content: "yes" }],
  ["meta", { name: "apple-mobile-web-app-status-bar-style", content: "black" },],
  ["meta", { name: "apple-mobile-web-app-title", content: "Dotfiles v0.2.462" },],
  ["meta", { name: "application-name", content: "Dotfiles v0.2.462" }],
  ["meta", { name: "author", content: "Sebastien Rousseau" }],
  ["meta", { name: "charset", content: "utf-8" }],
  ["meta", { name: "format-detection", content: "telephone=no" },],
  ["meta", { name: "msapplication-tap-highlight", content: "no" },],
  ["meta", { name: "msapplication-TileColor", content: "#9e00a3" },],
  ["meta", { name: "msapplication-TileImage", content: "/icons/dotfiles-192x192.png" },],
  ["meta", { name: "og:image:height", content: "627" }],
  ["meta", { name: "og:image:type", content: "image/png" }],
  ["meta", { name: "og:image:width", content: "1200" }],
  ["meta", { name: "og:image", content: "/logo.png" }],
  ["meta", { name: "og:locale", content: "en_GB" }],
  ["meta", { name: "og:robots", content: "all" }],
  ["meta", { name: "og:site_name", content: "Dotfiles (v0.2.462)" }],
  ["meta", { name: "og:type", content: "website" }],
  ["meta", { name: "og:url", content: "https://dotfiles.io/" }],
  ["meta", { name: "robots", content: "all" }],
  ["meta", { name: "theme-color", content: "#9e00a3" }],
  ["meta", { name: "twitter:creator", content: "@wwdseb" }],
  ["meta", { name: "twitter:image", content: "/logo.png" }]
  ["meta", { name: "twitter:site", content: "@wwdseb" }],
  ["meta", { name: "twitter:url", content: "https://dotfiles.io/" }],
  ["meta", { name: "viewport", content: "width=device-width, initial-scale=1" }],
];
