export const headers: string[] = [
  ["link", { rel: "icon", href: "/favicon.ico" }],
  ["link", { rel: "apple-touch-icon", href: "/icons/icon-192x192.png" }],
  ["link", { rel: "manifest", href: "/manifest.json" }],
  ["link", { rel: "stylesheet", href: "https://fonts.googleapis.com/css?family=Open+Sans:300,400,400i,700%7CRoboto+Mono&display=fallback" }],
  ["meta", { name: "theme-color", content: "#9e00a3" }],
  ["meta", { name: "viewport", content: "width=device-width, initial-scale=1" }],
  ["meta", { itemprop: "accessibilityAPI", content: "ARIA" }],
  ["meta", { itemprop: "accessibilityControl", content: "fullKeyboardControl" }],
  ["meta", { itemprop: "accessibilityControl", content: "fullMouseControl" }],
  ["meta", { itemprop: "accessibilityHazard", content: "noFlashingHazard" }],
  ["meta", { itemprop: "accessibilityHazard", content: "noMotionSimulationHazard" }],
  ["meta", { itemprop: "accessibilityHazard", content: "noSoundHazard" }],
  ["meta", { "http-equiv": "Cache-Control", content: "no-cache, no-store, must-revalidate" }],
  ["meta", { "http-equiv": "Pragma", content: "no-cache" }],
  ["meta", { "http-equiv": "Expires", content: "0" }],
  ["meta", { name: "apple-mobile-web-app-status-bar-style", content: "black" },],
  ["meta", { name: "apple-mobile-web-app-title", content: "Dotfiles v0.2.462" },],
  ["meta", { name: "application-name", content: "Dotfiles v0.2.462" }],
  ["meta", { name: "author", content: "Sebastien Rousseau" }],
  ["meta", { name: "format-detection", content: "telephone=no" },],
  ["meta", { name: "msapplication-tap-highlight", content: "no" },],
  ["meta", { name: "robots", content: "index, follow" }],
  ["meta", { name: "og:image:height", content: "627" }],
  ["meta", { name: "og:image:type", content: "image/png" }],
  ["meta", { name: "og:image:width", content: "1200" }],
  ["meta", { name: "og:image", content: "/logo.png" }],
  ["meta", { name: "og:robots", content: "index, follow" }],
  ["meta", { name: "og:site_name", content: "Dotfiles (v0.2.462)" }],
  ["meta", { name: "og:type", content: "website" }],
  ["meta", { name: "og:url", content: "https://dotfiles.io/" }],
  ["meta", { name: "twitter:creator", content: "@wwdseb" }],
  ["meta", { name: "twitter:site", content: "@wwdseb" }],
  ["meta", { name: "twitter:url", content: "https://dotfiles.io/" }],
  ["meta", { name: "twitter:image", content: "/logo.png" }]
];
