

export const arSidebar = {
  "/ar/": [
    {
      title: "البدء",
      collapsed: false,
      children: [
        "/ar/about/",
        "/ar/functions/",
        "/ar/paths/",
        "/ar/compatibility/",
        "/ar/guides/secret-management/",
        "/ar/guides/ssh-signing/",
        "/ar/guides/gpg-configuration/",
      ],
    },
    {
      title: "الأسماء المستعارة",
      collapsed: false,
      children: [
        "/ar/aliases/",
        "/ar/aliases/ai/",
        "/ar/aliases/archives/",
        "/ar/aliases/benchmarks/",
        "/ar/aliases/cd/",
        "/ar/aliases/chmod/",
        "/ar/aliases/clear/",
        "/ar/aliases/compliance/",
        "/ar/aliases/configuration/",
        "/ar/aliases/default/",
        "/ar/aliases/diagnostics/",
        "/ar/aliases/dig/",
        "/ar/aliases/disk-usage/",
        "/ar/aliases/docker/",
        "/ar/aliases/editor/",
        "/ar/aliases/find/",
        "/ar/aliases/fonts/",
        "/ar/aliases/gcloud/",
        "/ar/aliases/git/",
        "/ar/aliases/gnu/",
        "/ar/aliases/go/",
        "/ar/aliases/heroku/",
        "/ar/aliases/installer/",
        "/ar/aliases/interactive/",
        "/ar/aliases/kubernetes/",
        "/ar/aliases/legal/",
        "/ar/aliases/lua/",
        "/ar/aliases/macOS/",
        "/ar/aliases/make/",
        "/ar/aliases/mkdir/",
        "/ar/aliases/modern/",
        "/ar/aliases/npm/",
        "/ar/aliases/permission/",
        "/ar/aliases/pnpm/",
        "/ar/aliases/ps/",
        "/ar/aliases/python/",
        "/ar/aliases/rsync/",
        "/ar/aliases/rust/",
        "/ar/aliases/security/",
        "/ar/aliases/subversion/",
        "/ar/aliases/sudo/",
        "/ar/aliases/system/",
        "/ar/aliases/terraform/",
        "/ar/aliases/tmux/",
        "/ar/aliases/update/",
        "/ar/aliases/uuid/",
        "/ar/aliases/vagrant/",
        "/ar/aliases/wget/",
        "/ar/aliases/yarn/",
      ],
    },
  ],
};
