

export const heSidebar = {
  "/he/": [
    {
      title: "התחלה",
      collapsed: false,
      children: [
        "/he/about/",
        "/he/functions/",
        "/he/paths/",
        "/he/compatibility/",
        "/he/guides/secret-management/",
        "/he/guides/ssh-signing/",
        "/he/guides/gpg-configuration/",
      ],
    },
    {
      title: "כינויים",
      collapsed: false,
      children: [
        "/he/aliases/",
        "/he/aliases/ai/",
        "/he/aliases/archives/",
        "/he/aliases/benchmarks/",
        "/he/aliases/cd/",
        "/he/aliases/chmod/",
        "/he/aliases/clear/",
        "/he/aliases/compliance/",
        "/he/aliases/configuration/",
        "/he/aliases/default/",
        "/he/aliases/diagnostics/",
        "/he/aliases/dig/",
        "/he/aliases/disk-usage/",
        "/he/aliases/docker/",
        "/he/aliases/editor/",
        "/he/aliases/find/",
        "/he/aliases/fonts/",
        "/he/aliases/gcloud/",
        "/he/aliases/git/",
        "/he/aliases/gnu/",
        "/he/aliases/go/",
        "/he/aliases/heroku/",
        "/he/aliases/installer/",
        "/he/aliases/interactive/",
        "/he/aliases/kubernetes/",
        "/he/aliases/legal/",
        "/he/aliases/lua/",
        "/he/aliases/macOS/",
        "/he/aliases/make/",
        "/he/aliases/mkdir/",
        "/he/aliases/modern/",
        "/he/aliases/npm/",
        "/he/aliases/permission/",
        "/he/aliases/pnpm/",
        "/he/aliases/ps/",
        "/he/aliases/python/",
        "/he/aliases/rsync/",
        "/he/aliases/rust/",
        "/he/aliases/security/",
        "/he/aliases/subversion/",
        "/he/aliases/sudo/",
        "/he/aliases/system/",
        "/he/aliases/terraform/",
        "/he/aliases/tmux/",
        "/he/aliases/update/",
        "/he/aliases/uuid/",
        "/he/aliases/vagrant/",
        "/he/aliases/wget/",
        "/he/aliases/yarn/",
      ],
    },
  ],
};
