

export const jaSidebar = {
  "/ja/": [
    {
      title: "はじめに",
      collapsed: false,
      children: [
        "/ja/about/",
        "/ja/functions/",
        "/ja/paths/",
        "/ja/compatibility/",
        "/ja/guides/secret-management/",
        "/ja/guides/ssh-signing/",
        "/ja/guides/gpg-configuration/",
      ],
    },
    {
      title: "エイリアス",
      collapsed: false,
      children: [
        "/ja/aliases/",
        "/ja/aliases/ai/",
        "/ja/aliases/archives/",
        "/ja/aliases/cd/",
        "/ja/aliases/chmod/",
        "/ja/aliases/clear/",
        "/ja/aliases/compliance/",
        "/ja/aliases/configuration/",
        "/ja/aliases/default/",
        "/ja/aliases/diagnostics/",
        "/ja/aliases/dig/",
        "/ja/aliases/disk-usage/",
        "/ja/aliases/docker/",
        "/ja/aliases/editor/",
        "/ja/aliases/find/",
        "/ja/aliases/fonts/",
        "/ja/aliases/gcloud/",
        "/ja/aliases/git/",
        "/ja/aliases/gnu/",
        "/ja/aliases/go/",
        "/ja/aliases/heroku/",
        "/ja/aliases/installer/",
        "/ja/aliases/interactive/",
        "/ja/aliases/kubernetes/",
        "/ja/aliases/legal/",
        "/ja/aliases/lua/",
        "/ja/aliases/macOS/",
        "/ja/aliases/make/",
        "/ja/aliases/mkdir/",
        "/ja/aliases/modern/",
        "/ja/aliases/npm/",
        "/ja/aliases/permission/",
        "/ja/aliases/pnpm/",
        "/ja/aliases/ps/",
        "/ja/aliases/python/",
        "/ja/aliases/rsync/",
        "/ja/aliases/rust/",
        "/ja/aliases/security/",
        "/ja/aliases/subversion/",
        "/ja/aliases/sudo/",
        "/ja/aliases/terraform/",
        "/ja/aliases/tmux/",
        "/ja/aliases/update/",
        "/ja/aliases/uuid/",
        "/ja/aliases/wget/",
        "/ja/aliases/yarn/",
      ],
    },
  ],
};
