

export const koSidebar = {
  "/ko/": [
    {
      title: "시작하기",
      collapsed: false,
      children: [
        "/ko/about/",
        "/ko/functions/",
        "/ko/paths/",
        "/ko/compatibility/",
        "/ko/guides/secret-management/",
        "/ko/guides/ssh-signing/",
        "/ko/guides/gpg-configuration/",
      ],
    },
    {
      title: "별칭",
      collapsed: false,
      children: [
        "/ko/aliases/",
        "/ko/aliases/ai/",
        "/ko/aliases/archives/",
        "/ko/aliases/benchmarks/",
        "/ko/aliases/cd/",
        "/ko/aliases/chmod/",
        "/ko/aliases/clear/",
        "/ko/aliases/compliance/",
        "/ko/aliases/configuration/",
        "/ko/aliases/default/",
        "/ko/aliases/diagnostics/",
        "/ko/aliases/dig/",
        "/ko/aliases/disk-usage/",
        "/ko/aliases/docker/",
        "/ko/aliases/editor/",
        "/ko/aliases/find/",
        "/ko/aliases/fonts/",
        "/ko/aliases/gcloud/",
        "/ko/aliases/git/",
        "/ko/aliases/gnu/",
        "/ko/aliases/go/",
        "/ko/aliases/heroku/",
        "/ko/aliases/installer/",
        "/ko/aliases/interactive/",
        "/ko/aliases/kubernetes/",
        "/ko/aliases/legal/",
        "/ko/aliases/lua/",
        "/ko/aliases/macOS/",
        "/ko/aliases/make/",
        "/ko/aliases/mkdir/",
        "/ko/aliases/modern/",
        "/ko/aliases/npm/",
        "/ko/aliases/permission/",
        "/ko/aliases/pnpm/",
        "/ko/aliases/ps/",
        "/ko/aliases/python/",
        "/ko/aliases/rsync/",
        "/ko/aliases/rust/",
        "/ko/aliases/security/",
        "/ko/aliases/subversion/",
        "/ko/aliases/sudo/",
        "/ko/aliases/system/",
        "/ko/aliases/terraform/",
        "/ko/aliases/tmux/",
        "/ko/aliases/update/",
        "/ko/aliases/uuid/",
        "/ko/aliases/vagrant/",
        "/ko/aliases/wget/",
        "/ko/aliases/yarn/",
      ],
    },
  ],
};
