

export const plSidebar = {
  "/pl/": [
    {
      title: "Pierwsze Kroki",
      collapsed: false,
      children: [
        "/pl/about/",
        "/pl/functions/",
        "/pl/paths/",
        "/pl/compatibility/",
        "/pl/guides/secret-management/",
      ],
    },
    {
      title: "Aliasy",
      collapsed: false,
      children: [
        "/pl/aliases/",
        "/pl/aliases/ai/",
        "/pl/aliases/archives/",
        "/pl/aliases/cd/",
        "/pl/aliases/chmod/",
        "/pl/aliases/clear/",
        "/pl/aliases/compliance/",
        "/pl/aliases/configuration/",
        "/pl/aliases/default/",
        "/pl/aliases/diagnostics/",
        "/pl/aliases/dig/",
        "/pl/aliases/disk-usage/",
        "/pl/aliases/docker/",
        "/pl/aliases/editor/",
        "/pl/aliases/find/",
        "/pl/aliases/fonts/",
        "/pl/aliases/gcloud/",
        "/pl/aliases/git/",
        "/pl/aliases/gnu/",
        "/pl/aliases/go/",
        "/pl/aliases/heroku/",
        "/pl/aliases/installer/",
        "/pl/aliases/interactive/",
        "/pl/aliases/kubernetes/",
        "/pl/aliases/legal/",
        "/pl/aliases/lua/",
        "/pl/aliases/macOS/",
        "/pl/aliases/make/",
        "/pl/aliases/mkdir/",
        "/pl/aliases/modern/",
        "/pl/aliases/npm/",
        "/pl/aliases/permission/",
        "/pl/aliases/pnpm/",
        "/pl/aliases/ps/",
        "/pl/aliases/python/",
        "/pl/aliases/rsync/",
        "/pl/aliases/rust/",
        "/pl/aliases/security/",
        "/pl/aliases/subversion/",
        "/pl/aliases/sudo/",
        "/pl/aliases/terraform/",
        "/pl/aliases/tmux/",
        "/pl/aliases/update/",
        "/pl/aliases/uuid/",
        "/pl/aliases/wget/",
        "/pl/aliases/yarn/",
      ],
    },
  ],
};
