

export const roSidebar = {
  "/ro/": [
    {
      title: "Început",
      collapsed: false,
      children: [
        "/ro/about/",
        "/ro/functions/",
        "/ro/paths/",
        "/ro/compatibility/",
        "/ro/guides/secret-management/",
      ],
    },
    {
      title: "Aliasuri",
      collapsed: false,
      children: [
        "/ro/aliases/",
        "/ro/aliases/ai/",
        "/ro/aliases/archives/",
        "/ro/aliases/cd/",
        "/ro/aliases/chmod/",
        "/ro/aliases/clear/",
        "/ro/aliases/compliance/",
        "/ro/aliases/configuration/",
        "/ro/aliases/default/",
        "/ro/aliases/diagnostics/",
        "/ro/aliases/dig/",
        "/ro/aliases/disk-usage/",
        "/ro/aliases/docker/",
        "/ro/aliases/editor/",
        "/ro/aliases/find/",
        "/ro/aliases/fonts/",
        "/ro/aliases/gcloud/",
        "/ro/aliases/git/",
        "/ro/aliases/gnu/",
        "/ro/aliases/go/",
        "/ro/aliases/heroku/",
        "/ro/aliases/installer/",
        "/ro/aliases/interactive/",
        "/ro/aliases/kubernetes/",
        "/ro/aliases/legal/",
        "/ro/aliases/lua/",
        "/ro/aliases/macOS/",
        "/ro/aliases/make/",
        "/ro/aliases/mkdir/",
        "/ro/aliases/modern/",
        "/ro/aliases/npm/",
        "/ro/aliases/permission/",
        "/ro/aliases/pnpm/",
        "/ro/aliases/ps/",
        "/ro/aliases/python/",
        "/ro/aliases/rsync/",
        "/ro/aliases/rust/",
        "/ro/aliases/security/",
        "/ro/aliases/subversion/",
        "/ro/aliases/sudo/",
        "/ro/aliases/terraform/",
        "/ro/aliases/tmux/",
        "/ro/aliases/update/",
        "/ro/aliases/uuid/",
        "/ro/aliases/wget/",
        "/ro/aliases/yarn/",
      ],
    },
  ],
};
