

export const ruSidebar = {
  "/ru/": [
    {
      title: "Начало работы",
      collapsed: false,
      children: [
        "/ru/about/",
        "/ru/functions/",
        "/ru/paths/",
        "/ru/compatibility/",
        "/ru/guides/secret-management/",
      ],
    },
    {
      title: "Псевдонимы",
      collapsed: false,
      children: [
        "/ru/alias/",
        "/ru/alias/ai/",
        "/ru/alias/archives/",
        "/ru/alias/cd/",
        "/ru/alias/chmod/",
        "/ru/alias/clear/",
        "/ru/alias/compliance/",
        "/ru/alias/configuration/",
        "/ru/alias/default/",
        "/ru/alias/diagnostics/",
        "/ru/alias/dig/",
        "/ru/alias/disk-usage/",
        "/ru/alias/docker/",
        "/ru/alias/editor/",
        "/ru/alias/find/",
        "/ru/alias/fonts/",
        "/ru/alias/gcloud/",
        "/ru/alias/git/",
        "/ru/alias/gnu/",
        "/ru/alias/go/",
        "/ru/alias/heroku/",
        "/ru/alias/installer/",
        "/ru/alias/interactive/",
        "/ru/alias/kubernetes/",
        "/ru/alias/legal/",
        "/ru/alias/lua/",
        "/ru/alias/macOS/",
        "/ru/alias/make/",
        "/ru/alias/mkdir/",
        "/ru/alias/modern/",
        "/ru/alias/npm/",
        "/ru/alias/permission/",
        "/ru/alias/pnpm/",
        "/ru/alias/ps/",
        "/ru/alias/python/",
        "/ru/alias/rsync/",
        "/ru/alias/rust/",
        "/ru/alias/security/",
        "/ru/alias/subversion/",
        "/ru/alias/sudo/",
        "/ru/alias/terraform/",
        "/ru/alias/tmux/",
        "/ru/alias/update/",
        "/ru/alias/uuid/",
        "/ru/alias/wget/",
        "/ru/alias/yarn/",
      ],
    },
  ],
};
