

export const ruSidebar = {
  "/ru/": [
    {
      title: "Начало работы",
      collapsed: false,
      children: [
        "/ru/about/",
        "/ru/functions/",
        "/ru/paths/",
        "/ru/compatibility/",
        "/ru/guides/secret-management/",
        "/ru/guides/ssh-signing/",
        "/ru/guides/gpg-configuration/",
      ],
    },
    {
      title: "Псевдонимы",
      collapsed: false,
      children: [
        "/ru/aliases/",
        "/ru/aliases/ai/",
        "/ru/aliases/archives/",
        "/ru/aliases/cd/",
        "/ru/aliases/chmod/",
        "/ru/aliases/clear/",
        "/ru/aliases/compliance/",
        "/ru/aliases/configuration/",
        "/ru/aliases/default/",
        "/ru/aliases/diagnostics/",
        "/ru/aliases/dig/",
        "/ru/aliases/disk-usage/",
        "/ru/aliases/docker/",
        "/ru/aliases/editor/",
        "/ru/aliases/find/",
        "/ru/aliases/fonts/",
        "/ru/aliases/gcloud/",
        "/ru/aliases/git/",
        "/ru/aliases/gnu/",
        "/ru/aliases/go/",
        "/ru/aliases/heroku/",
        "/ru/aliases/installer/",
        "/ru/aliases/interactive/",
        "/ru/aliases/kubernetes/",
        "/ru/aliases/legal/",
        "/ru/aliases/lua/",
        "/ru/aliases/macOS/",
        "/ru/aliases/make/",
        "/ru/aliases/mkdir/",
        "/ru/aliases/modern/",
        "/ru/aliases/npm/",
        "/ru/aliases/permission/",
        "/ru/aliases/pnpm/",
        "/ru/aliases/ps/",
        "/ru/aliases/python/",
        "/ru/aliases/rsync/",
        "/ru/aliases/rust/",
        "/ru/aliases/security/",
        "/ru/aliases/subversion/",
        "/ru/aliases/sudo/",
        "/ru/aliases/terraform/",
        "/ru/aliases/tmux/",
        "/ru/aliases/update/",
        "/ru/aliases/uuid/",
        "/ru/aliases/wget/",
        "/ru/aliases/yarn/",
      ],
    },
  ],
};
