

export const thSidebar = {
  "/th/": [
    {
      title: "เริ่มต้น",
      collapsed: false,
      children: [
        "/th/about/",
        "/th/functions/",
        "/th/paths/",
        "/th/compatibility/",
        "/th/guides/secret-management/",
        "/th/guides/ssh-signing/",
        "/th/guides/gpg-configuration/",
      ],
    },
    {
      title: "นามแฝง",
      collapsed: false,
      children: [
        "/th/aliases/",
        "/th/aliases/ai/",
        "/th/aliases/archives/",
        "/th/aliases/cd/",
        "/th/aliases/chmod/",
        "/th/aliases/clear/",
        "/th/aliases/compliance/",
        "/th/aliases/configuration/",
        "/th/aliases/default/",
        "/th/aliases/diagnostics/",
        "/th/aliases/dig/",
        "/th/aliases/disk-usage/",
        "/th/aliases/docker/",
        "/th/aliases/editor/",
        "/th/aliases/find/",
        "/th/aliases/fonts/",
        "/th/aliases/gcloud/",
        "/th/aliases/git/",
        "/th/aliases/gnu/",
        "/th/aliases/go/",
        "/th/aliases/heroku/",
        "/th/aliases/installer/",
        "/th/aliases/interactive/",
        "/th/aliases/kubernetes/",
        "/th/aliases/legal/",
        "/th/aliases/lua/",
        "/th/aliases/macOS/",
        "/th/aliases/make/",
        "/th/aliases/mkdir/",
        "/th/aliases/modern/",
        "/th/aliases/npm/",
        "/th/aliases/permission/",
        "/th/aliases/pnpm/",
        "/th/aliases/ps/",
        "/th/aliases/python/",
        "/th/aliases/rsync/",
        "/th/aliases/rust/",
        "/th/aliases/security/",
        "/th/aliases/subversion/",
        "/th/aliases/sudo/",
        "/th/aliases/terraform/",
        "/th/aliases/tmux/",
        "/th/aliases/update/",
        "/th/aliases/uuid/",
        "/th/aliases/wget/",
        "/th/aliases/yarn/",
      ],
    },
  ],
};
