

export const trSidebar = {
  "/tr/": [
    {
      title: "Başlarken",
      collapsed: false,
      children: [
        "/tr/about/",
        "/tr/functions/",
        "/tr/paths/",
        "/tr/compatibility/",
        "/tr/guides/secret-management/",
        "/tr/guides/ssh-signing/",
        "/tr/guides/gpg-configuration/",
      ],
    },
    {
      title: "Takma Adlar",
      collapsed: false,
      children: [
        "/tr/aliases/",
        "/tr/aliases/ai/",
        "/tr/aliases/archives/",
        "/tr/aliases/cd/",
        "/tr/aliases/chmod/",
        "/tr/aliases/clear/",
        "/tr/aliases/compliance/",
        "/tr/aliases/configuration/",
        "/tr/aliases/default/",
        "/tr/aliases/diagnostics/",
        "/tr/aliases/dig/",
        "/tr/aliases/disk-usage/",
        "/tr/aliases/docker/",
        "/tr/aliases/editor/",
        "/tr/aliases/find/",
        "/tr/aliases/fonts/",
        "/tr/aliases/gcloud/",
        "/tr/aliases/git/",
        "/tr/aliases/gnu/",
        "/tr/aliases/go/",
        "/tr/aliases/heroku/",
        "/tr/aliases/installer/",
        "/tr/aliases/interactive/",
        "/tr/aliases/kubernetes/",
        "/tr/aliases/legal/",
        "/tr/aliases/lua/",
        "/tr/aliases/macOS/",
        "/tr/aliases/make/",
        "/tr/aliases/mkdir/",
        "/tr/aliases/modern/",
        "/tr/aliases/npm/",
        "/tr/aliases/permission/",
        "/tr/aliases/pnpm/",
        "/tr/aliases/ps/",
        "/tr/aliases/python/",
        "/tr/aliases/rsync/",
        "/tr/aliases/rust/",
        "/tr/aliases/security/",
        "/tr/aliases/subversion/",
        "/tr/aliases/sudo/",
        "/tr/aliases/terraform/",
        "/tr/aliases/tmux/",
        "/tr/aliases/update/",
        "/tr/aliases/uuid/",
        "/tr/aliases/wget/",
        "/tr/aliases/yarn/",
      ],
    },
  ],
};
