

export const ukSidebar = {
  "/uk/": [
    {
      title: "Початок",
      collapsed: false,
      children: [
        "/uk/about/",
        "/uk/functions/",
        "/uk/paths/",
        "/uk/compatibility/",
        "/uk/guides/secret-management/",
        "/uk/guides/ssh-signing/",
        "/uk/guides/gpg-configuration/",
      ],
    },
    {
      title: "Аліаси",
      collapsed: false,
      children: [
        "/uk/aliases/",
        "/uk/aliases/ai/",
        "/uk/aliases/archives/",
        "/uk/aliases/cd/",
        "/uk/aliases/chmod/",
        "/uk/aliases/clear/",
        "/uk/aliases/compliance/",
        "/uk/aliases/configuration/",
        "/uk/aliases/default/",
        "/uk/aliases/diagnostics/",
        "/uk/aliases/dig/",
        "/uk/aliases/disk-usage/",
        "/uk/aliases/docker/",
        "/uk/aliases/editor/",
        "/uk/aliases/find/",
        "/uk/aliases/fonts/",
        "/uk/aliases/gcloud/",
        "/uk/aliases/git/",
        "/uk/aliases/gnu/",
        "/uk/aliases/go/",
        "/uk/aliases/heroku/",
        "/uk/aliases/installer/",
        "/uk/aliases/interactive/",
        "/uk/aliases/kubernetes/",
        "/uk/aliases/legal/",
        "/uk/aliases/lua/",
        "/uk/aliases/macOS/",
        "/uk/aliases/make/",
        "/uk/aliases/mkdir/",
        "/uk/aliases/modern/",
        "/uk/aliases/npm/",
        "/uk/aliases/permission/",
        "/uk/aliases/pnpm/",
        "/uk/aliases/ps/",
        "/uk/aliases/python/",
        "/uk/aliases/rsync/",
        "/uk/aliases/rust/",
        "/uk/aliases/security/",
        "/uk/aliases/subversion/",
        "/uk/aliases/sudo/",
        "/uk/aliases/terraform/",
        "/uk/aliases/tmux/",
        "/uk/aliases/update/",
        "/uk/aliases/uuid/",
        "/uk/aliases/wget/",
        "/uk/aliases/yarn/",
      ],
    },
  ],
};
