

export const viSidebar = {
  "/vi/": [
    {
      title: "Bắt Đầu",
      collapsed: false,
      children: [
        "/vi/about/",
        "/vi/functions/",
        "/vi/paths/",
        "/vi/compatibility/",
        "/vi/guides/secret-management/",
        "/vi/guides/ssh-signing/",
        "/vi/guides/gpg-configuration/",
      ],
    },
    {
      title: "Bí Danh",
      collapsed: false,
      children: [
        "/vi/aliases/",
        "/vi/aliases/ai/",
        "/vi/aliases/archives/",
        "/vi/aliases/cd/",
        "/vi/aliases/chmod/",
        "/vi/aliases/clear/",
        "/vi/aliases/compliance/",
        "/vi/aliases/configuration/",
        "/vi/aliases/default/",
        "/vi/aliases/diagnostics/",
        "/vi/aliases/dig/",
        "/vi/aliases/disk-usage/",
        "/vi/aliases/docker/",
        "/vi/aliases/editor/",
        "/vi/aliases/find/",
        "/vi/aliases/fonts/",
        "/vi/aliases/gcloud/",
        "/vi/aliases/git/",
        "/vi/aliases/gnu/",
        "/vi/aliases/go/",
        "/vi/aliases/heroku/",
        "/vi/aliases/installer/",
        "/vi/aliases/interactive/",
        "/vi/aliases/kubernetes/",
        "/vi/aliases/legal/",
        "/vi/aliases/lua/",
        "/vi/aliases/macOS/",
        "/vi/aliases/make/",
        "/vi/aliases/mkdir/",
        "/vi/aliases/modern/",
        "/vi/aliases/npm/",
        "/vi/aliases/permission/",
        "/vi/aliases/pnpm/",
        "/vi/aliases/ps/",
        "/vi/aliases/python/",
        "/vi/aliases/rsync/",
        "/vi/aliases/rust/",
        "/vi/aliases/security/",
        "/vi/aliases/subversion/",
        "/vi/aliases/sudo/",
        "/vi/aliases/terraform/",
        "/vi/aliases/tmux/",
        "/vi/aliases/update/",
        "/vi/aliases/uuid/",
        "/vi/aliases/wget/",
        "/vi/aliases/yarn/",
      ],
    },
  ],
};
