

export const zhtwSidebar = {
  "/zh-tw/": [
    {
      title: "開始使用",
      collapsed: false,
      children: [
        "/zh-tw/about/",
        "/zh-tw/functions/",
        "/zh-tw/paths/",
        "/zh-tw/compatibility/",
        "/zh-tw/guides/secret-management/",
      ],
    },
    {
      title: "別名",
      collapsed: false,
      children: [
        "/zh-tw/aliases/",
        "/zh-tw/aliases/ai/",
        "/zh-tw/aliases/archives/",
        "/zh-tw/aliases/cd/",
        "/zh-tw/aliases/chmod/",
        "/zh-tw/aliases/clear/",
        "/zh-tw/aliases/compliance/",
        "/zh-tw/aliases/configuration/",
        "/zh-tw/aliases/default/",
        "/zh-tw/aliases/diagnostics/",
        "/zh-tw/aliases/dig/",
        "/zh-tw/aliases/disk-usage/",
        "/zh-tw/aliases/docker/",
        "/zh-tw/aliases/editor/",
        "/zh-tw/aliases/find/",
        "/zh-tw/aliases/fonts/",
        "/zh-tw/aliases/gcloud/",
        "/zh-tw/aliases/git/",
        "/zh-tw/aliases/gnu/",
        "/zh-tw/aliases/go/",
        "/zh-tw/aliases/heroku/",
        "/zh-tw/aliases/installer/",
        "/zh-tw/aliases/interactive/",
        "/zh-tw/aliases/kubernetes/",
        "/zh-tw/aliases/legal/",
        "/zh-tw/aliases/lua/",
        "/zh-tw/aliases/macOS/",
        "/zh-tw/aliases/make/",
        "/zh-tw/aliases/mkdir/",
        "/zh-tw/aliases/modern/",
        "/zh-tw/aliases/npm/",
        "/zh-tw/aliases/permission/",
        "/zh-tw/aliases/pnpm/",
        "/zh-tw/aliases/ps/",
        "/zh-tw/aliases/python/",
        "/zh-tw/aliases/rsync/",
        "/zh-tw/aliases/rust/",
        "/zh-tw/aliases/security/",
        "/zh-tw/aliases/subversion/",
        "/zh-tw/aliases/sudo/",
        "/zh-tw/aliases/terraform/",
        "/zh-tw/aliases/tmux/",
        "/zh-tw/aliases/update/",
        "/zh-tw/aliases/uuid/",
        "/zh-tw/aliases/wget/",
        "/zh-tw/aliases/yarn/",
      ],
    },
  ],
};
